org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:/Users/Alex/.jdks/corretto-20.0.2.1
android.enableR8.fullMode=false

# Fix for sign_in_with_apple plugin
android.jetifier.ignorelist=bcprov-jdk15on
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Network and offline mode settings
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
# Uncomment the line below if you want to use offline mode
#org.gradle.offline=true

# Connection timeout settings
systemProp.http.connectionTimeout=180000
systemProp.http.socketTimeout=180000
systemProp.https.connectionTimeout=180000
systemProp.https.socketTimeout=180000

